# Generated by Django 2.2.2 on 2020-05-27 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_title', models.CharField(max_length=200)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('genre', models.CharField(max_length=100)),
                ('summary', models.TextField(null=True)),
            ],
            options={
                'ordering': ['film_title'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('image_u', models.TextField(blank=True, null=True)),
                ('photo_film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='movies_app.Film')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('film_comment', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='movies_app.Film')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
    ]
